model:
  - GraphSAGE
device:
  - cpu
batch_size:
  - 32
learning_rate:
  - 0.0001
  # - 0.01
  - 0.001
l2:
  - 0.
classifier_epochs:
  - 1000
optimizer:
  - Adam
scheduler:
  - null
loss:
  - MulticlassClassificationLoss
gradient_clipping:
  - null
early_stopper:
  -
    class: Patience
    args:
      patience: 100
      use_loss: False
shuffle:
  - True
dim_embedding:
  # - 16
  - 32
  - 64
num_layers:
  - 3
  # - 5
aggregation:
  - mean
  # - sum
